/* eslint-disable no-bitwise */
export enum ComponentType {
  SOLID_BODY = 1 << 0,
  SENSOR = 1 << 1,
  RENDER = 1 << 2,
  MOTOR = 1 << 3,
  SOURCE = 1 << 4,
  TRANSFORMABLE = 1 << 5,
  CONNECTION = 1 << 6,
  SOLID_BODY_RECT = 1 << 7,
  SOLID_BODY_CIRCLE = 1 << 8,
  NAME = 1 << 9,
  COLLISION = 1 << 10,
}

export enum SubstanceType {
  LIGHT = 1 << 1,
  BARRIER = 1 << 2,
}

export enum EmissionType {
  GAUSSIAN = 'GAUSSIAN',
  FLAT = 'FLAT',
}

export enum SensorActivation {
  EXCITATORY = 'EXCITATORY',
  INHIBITORY = 'INHIBITORY',
}

export enum EventType {
  APPLY_FORCE = 'APPLY_FORCE',
  SENSOR_ACTIVE = 'SENSOR_ACTIVE',
  REACTION = 'REACTION',
  ENTITY_CREATED = 'ENTITY_CREATED',
  ENTITY_DESTROYED = 'ENTITY_DESTROYED',
  ENTITY_COMPONENT_ADDED = 'ENTITY_COMPONENT_ADDED',
  ENTITY_COMPONENT_REMOVED = 'ENTITY_COMPONENT_REMOVED',
  SOURCE_CREATED = 'SOURCE_CREATED',
  SENSOR_CREATED = 'SENSOR_CREATED',
  SOURCE_DESTROYED = 'SOURCE_DESTROYED',
  SENSOR_DESTROYED = 'SENSOR_DESTROYED',
}
